version: '3.3'
services: 
  database:
    container_name: mysql
    image: mysql
    env_file: ./.env
    ports:
      - 3308:3306
    networks:
      - test-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpass
      - MYSQL_DATABASE=cognixus
networks:
  test-network:
    name: test-network